blank_issues_enabled: false
contact_links:
  - name: 💬 Support via Discord
    url: https://discord.gg/overseerr
    about: Chat with other users and the StreamNet VOD dev team
  - name: 💬 Ask a question (Discussions)
    url: https://github.com/cyb3rgh05t/streamnetvod/discussions
    about: Ask questions and discuss with other community members
